package flag

var regions = map[string]string{
	"asia-east1":              "Taiwan",
	"asia-east2":              "Hong Kong",
	"asia-northeast1":         "Tokyo",
	"asia-northeast2":         "Osaka",
	"asia-northeast3":         "Seoul, South Korea",
	"asia-south1":             "Mumbai, India",
	"asia-southeast1":         "Singapore",
	"asia-southeast2":         "Jakarta",
	"australia-southeast1":    "Sydney",
	"europe-central2":         "Warsaw, Poland",
	"europe-west1":            "Belgium",
	"europe-west2":            "London, UK",
	"europe-west3":            "Frankfurt, Germany",
	"europe-west6":            "Zurich, Switzerland",
	"northamerica-northeast1": "Montreal",
	"southamerica-east1":      "Sao Paulo, Brazil",
	"us-central1":             "Iowa",
	"us-east1":                "South Carolina",
	"us-east4":                "Northern Virginia",
	"us-west1":                "Oregon",
	"us-west2":                "Los Angeles",
	"us-west3":                "Salt Lake City",
	"us-west4":                "Las Vegas",
	// "asia-south2":             "Delhi, India",
	// "australia-southeast2":    "Melbourne",
	// "europe-north1":           "Finland",
	// "europe-southwest1":       "Madrid",
	// "europe-west4":            "Netherlands",
	// "europe-west8":            "Milan",
	// "europe-west9":            "Paris",
	// "northamerica-northeast2": "Toronto",
	// "southamerica-west1":      "Santiago, Chile",
	// "us-east5":                "Columbus",
}

var probes = map[string]interface{}{
	"ping":       nil,
	"traceroute": nil,
	"httpstat":   nil,
	"null":       nil,
	"curl":       nil,
}
